Repo:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '.vscode/**/*'
    - 'docs/**/*'
    - 'scripts/**/*'
    - 'test/**/*'
    - 'tools/**/*'
    - '.codebeatignore'
    - '.codebeatsettings'
    - '.editorconfig'
    - '.git*'
    - 'biome.json'
    - 'libmysql.dll'
    - 'LICENSE'
    - 'README.md'
    - 'SpacemanDMM.toml'

Map:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmm'

Icons:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmi'

Sound:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.aif'
    - '**/*.aiff'
    - '**/*.it'
    - '**/*.mid'
    - '**/*.midi'
    - '**/*.mod'
    - '**/*.mp3'
    - '**/*.ogg'
    - '**/*.oxm'
    - '**/*.raw'
    - '**/*.s3m'
    - '**/*.wma'
    - '**/*.wav'
    - '**/*.xm'

Config Update:
- changed-files:
  - any-glob-to-any-file:
    - 'config/example/**/*'

Database:
- changed-files:
  - any-glob-to-any-file:
    - 'sql/**/*'

Awaymaps:
- changed-files:
  - any-glob-to-any-file:
    - maps/away/**/*

Nerva:
- changed-files:
  - any-glob-to-any-file:
    - maps/nerva/**/*

Glloydstation:
- changed-files:
  - any-glob-to-any-file:
    - maps/glloydstation/**/*

Wyrm:
- changed-files:
  - any-glob-to-any-file:
    - maps/wyrm/**/*
