name: Run Tests

on:
  push:
    branches:
      - master
      - baymerge-testing
  pull_request:
    branches:
      - master
      - baymerge-testing
  workflow_dispatch: # allows this workflow to be manually triggered
env:
  BYOND_MAJOR: "515"
  BYOND_MINOR: "1647"
  SPACEMAN_DMM_VERSION: suite-1.9

jobs:
  PreFlight:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  DreamChecker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  |
          chmod +x ./scripts/install-spaceman-dmm.sh
          ./scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() && !env.ACT }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  Code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() && !env.ACT }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  Maps:
    runs-on: ubuntu-22.04
    needs: DreamChecker
    strategy:
      matrix:
        map_path: [example, nerva]
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: ${{ matrix.map_path }}
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() && !env.ACT }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  AwayMaps:
    runs-on: ubuntu-22.04
    needs: DreamChecker
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Check Away Sites Testing
        run: test/check-away-testing.sh
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        if: ${{ success() }}
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() && !env.ACT }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
  Templates:
    runs-on: ubuntu-22.04
    needs: DreamChecker
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: template_testing
          TEMPLATES: true
        run: test/run-test.sh
      - name: Run Failure Webhook
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        if: ${{ failure() && !env.ACT }}
        run: |
          wget https://raw.githubusercontent.com/DiscordHooks/github-actions-discord-webhook/master/send.sh
          chmod +x send.sh
          ./send.sh failure $WEBHOOK_URL
